version: '3.9'
services:
  voicevox:
    image: voicevox/voicevox_engine:nvidia-0.14.4@sha256:1817f3b6c15d257a9475ba000319da4405b1a9b6b2123ddb0363abae30b5e5ce
    hostname: voicevox
    container_name: voicevox__voicevox
    restart: unless-stopped

    networks:
      - default

    deploy:
      resources:
        limits:
          memory: 16g
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]

  cloudflared:
    image: cloudflare/cloudflared:2023.8.0-amd64@sha256:7edeb1ca407e8ff1026fb2835bf3922f782eedf99a10a7f6b6a685a3e265130e
    hostname: cloudflared
    container_name: voicevox__cloudflared
    restart: unless-stopped

    environment:
      TUNNEL_METRICS: 0.0.0.0:9126
      TUNNEL_LOGFILE: /dev/stdout

    command: tunnel run --token ${TUNNEL_TOKEN}
    user: root

    networks:
      default:
      outband:
      prometheus__cloudflared:
        aliases:
          - voicevox__cloudflared

    deploy:
      resources:
        limits:
          memory: 128m

networks:
  prometheus__cloudflared:
    name: prometheus__cloudflared
    external: true

  default:
    name: voicevox__default
    internal: true

  outband:
    name: voicevox__outband
