version: '3.9'
services:
  voicevox:
    image: voicevox/voicevox_engine:nvidia-0.14.4@sha256:1817f3b6c15d257a9475ba000319da4405b1a9b6b2123ddb0363abae30b5e5ce
    hostname: voicevox
    container_name: voicevox__voicevox
    restart: unless-stopped

    networks:
      - default

    deploy:
      resources:
        limits:
          memory: 16g
        reservations:
          devices:
            - driver: nvidia
              # Fix for docker-ce 27.3.x bugs.
              # refs:
              #   https://x.com/yanorei32/status/1840455188928405554
              #   https://github.com/moby/moby/pull/48483
              #   https://docs.docker.com/compose/how-tos/gpu-support/
              count: all
              capabilities: [gpu]

  cloudflared:
    image: cloudflare/cloudflared:2025.4.0-amd64@sha256:1bc361540d79ce61f3d0ba6997a363546b79fa08b10b3278fcb9eb722e561f69
    hostname: cloudflared
    container_name: voicevox__cloudflared
    restart: unless-stopped

    environment:
      TUNNEL_METRICS: 0.0.0.0:9126
      TUNNEL_LOGFILE: /dev/stdout

    command: tunnel run --token ${TUNNEL_TOKEN}
    user: root

    networks:
      default:
      outband:
      prometheus__cloudflared:
        aliases:
          - voicevox__cloudflared

    deploy:
      resources:
        limits:
          memory: 128m

networks:
  prometheus__cloudflared:
    name: prometheus__cloudflared
    external: true

  default:
    name: voicevox__default
    internal: true

  outband:
    name: voicevox__outband
