version: '3.9'
services:
  voicevox:
    image: voicevox/voicevox_engine:nvidia-0.24.1@sha256:07c2f53a61ad65ba73539ac759212127ff9c95a3815fff14c6b6f4904db89a98
    hostname: voicevox
    container_name: voicevox__voicevox
    restart: unless-stopped

    networks:
      - default

    runtime: nvidia

    deploy:
      resources:
        limits:
          memory: 16g

  cloudflared:
    image: cloudflare/cloudflared:2025.9.0-amd64@sha256:3a0095706dafda51403bd1c4bfc5c293979d4978542d4a52385d9cee2c9ef870
    hostname: cloudflared
    container_name: voicevox__cloudflared
    restart: unless-stopped

    environment:
      TUNNEL_METRICS: 0.0.0.0:9126
      TUNNEL_LOGFILE: /dev/stdout

    command: tunnel run --token ${TUNNEL_TOKEN}
    user: root

    networks:
      default:
      outband:
      prometheus__cloudflared:
        aliases:
          - voicevox__cloudflared

    deploy:
      resources:
        limits:
          memory: 128m

networks:
  prometheus__cloudflared:
    name: prometheus__cloudflared
    external: true

  default:
    name: voicevox__default
    internal: true

  outband:
    name: voicevox__outband
